const alImran = [
  { verse: 1, arabic: "الم", english: "Alif, Lam, Meem" },
  { verse: 2, arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ", english: "Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence." },
  { verse: 3, arabic: "نَزَّلَ عَلَيْكَ الْكِتَابَ بِالْحَقِّ مُصَدِّقًا لِمَا بَيْنَ يَدَيْهِ وَأَنْزَلَ التَّوْرَاةَ وَالْإِنجِيلَ", english: "He has sent down upon you, [O Muhammad], the Book in truth, confirming what was before it. And He revealed the Torah and the Gospel." },
  { verse: 4, arabic: "مِن قَبْلُ هُدًى لِّلنَّاسِ وَأَنزَلَ الْفُرْقَانَ ۗ إِنَّ الَّذِينَ كَفَرُوا بِآيَاتِ اللَّهِ لَهُمْ عَذَابٌ شَدِيدٌ ۗ وَاللَّهُ عَزِيزٌ ذُو ٱنتِقَامٍ", english: "Before, as guidance for the people. And He revealed the Criterion [the Qur'an]. Indeed, those who disbelieve in the verses of Allah will have a severe punishment, and Allah is Exalted in Might, the Owner of Retribution." },
  { verse: 5, arabic: "إِنَّ اللَّهَ لَا يَخْفَىٰ عَلَيْهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ", english: "Indeed, from Allah nothing is hidden in the earth nor in the heaven." },
  { verse: 6, arabic: "هُوَ الَّذِي يُصَوِّرُكُمْ فِي الْأَرْحَامِ كَيْفَ يَشَاءُ ۚ لَا إِلَٰهَ إِلَّا هُوَ الْعَزِيزُ الْحَكِيمُ", english: "It is He who forms you in the wombs however He wills. There is no deity except Him, the Exalted in Might, the Wise." },
  { verse: 7, arabic: "هُوَ الَّذِي أَنزَلَ عَلَيْكَ الْكِتَابَ مِنْهُ آيَاتٌ مُّحْكَمَاتٌ هُنَّ أُمُّ الْكِتَابِ وَأُخَرُ مُتَشَابِهَاتٌ...", english: "It is He who has sent down to you, [O Muhammad], the Book; in it are verses that are precise - they are the foundation of the Book - and others unspecific..." },
  { verse: 8, arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ الْوَهَّابُ", english: "Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower." },
  { verse: 9, arabic: "رَبَّنَا إِنَّكَ جَامِعُ النَّاسِ لِيَوْمٍ لَّا رَيْبَ فِيهِ ۚ إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ", english: "Our Lord, surely You will gather the people for a Day about which there is no doubt. Indeed, Allah does not fail in His promise." },
  { verse: 10, arabic: "إِنَّ الَّذِينَ كَفَرُوا لَن تُغْنِيَ عَنْهُمْ أَمْوَالُهُمْ وَلَا أَوْلَادُهُم مِّنَ اللَّهِ شَيْئًا ۖ وَأُولَٰئِكَ هُمْ وَقُودُ النَّارِ", english: "Indeed, those who disbelieve - never will their wealth or their children avail them against Allah at all. And it is they who are fuel for the Fire." },
  { verse: 11, arabic: "كَدَأْبِ آلِ فِرْعَوْنَ وَالَّذِينَ مِن قَبْلِهِمْ ۚ كَذَّبُوا بِآيَاتِنَا فَأَخَذَهُمُ اللَّهُ بِذُنُوبِهِمْ ۗ وَاللَّهُ شَدِيدُ الْعِقَابِ", english: "[Theirs is] like the custom of the people of Pharaoh and of those before them. They denied Our signs, so Allah seized them for their sins. And Allah is severe in penalty." },
  { verse: 12, arabic: "قُل لِّلَّذِينَ كَفَرُوا سَتُغْلَبُونَ وَتُحْشَرُونَ إِلَىٰ جَهَنَّمَ ۚ وَبِئْسَ الْمِهَادُ", english: "Say to those who disbelieve, 'You will be overcome and gathered together to Hell, and wretched is the resting place.'" },
  { verse: 13, arabic: "قَدْ كَانَ لَكُمْ آيَةٌ فِي فِئَتَيْنِ الْتَقَتَا...", english: "Already there has been for you a sign in the two armies that met..." },
  { verse: 14, arabic: "زُيِّنَ لِلنَّاسِ حُبُّ الشَّهَوَاتِ...", english: "Beautified for people is the love of that which they desire..." },
  { verse: 15, arabic: "قُلْ أَؤُنَبِّئُكُم بِخَيْرٍ مِّن ذَٰلِكُمْ...", english: "Say, 'Shall I inform you of [something] better than that?'..." },
  { verse: 16, arabic: "الَّذِينَ يَقُولُونَ رَبَّنَا إِنَّنَا آمَنَّا...", english: "Those who say, 'Our Lord, indeed we have believed...'" },
  { verse: 17, arabic: "الصَّابِرِينَ وَالصَّادِقِينَ...", english: "The patient, the true, the obedient..." },
  { verse: 18, arabic: "شَهِدَ اللَّهُ أَنَّهُ لَا إِلَٰهَ إِلَّا هُوَ...", english: "Allah witnesses that there is no deity except Him..." },
  { verse: 19, arabic: "إِنَّ الدِّينَ عِندَ اللَّهِ الْإِسْلَامُ...", english: "Indeed, the religion in the sight of Allah is Islam..." },
  { verse: 20, arabic: "فَإِنْ حَاجُّوكَ فَقُلْ أَسْلَمْتُ...", english: "So if they argue with you, say, 'I have submitted myself to Allah...'" }
];
